---
kind: pipeline
type: docker
name: pcgc

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.13
    commands:
      - make test
    volumes:
      - name: deps
        path: /go

  - name: lint
    image: golangci/golangci-lint:v1.23.3
    commands:
      - make lint

  - name: build
    image: golang:1.13
    commands:
      - make build
    volumes:
      - name: deps
        path: /go

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
